version: "3.9"
services:
  frontend-catalog:
    image: ghcr.io/azenith-solutions/frontend-website-catalog-app:${IMAGE_TAG}
    container_name: site
    restart: unless-stopped
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://127.0.0.1:8081/health || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3
