name: hardwaretech

services:
  frontend-catalog:
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"                   
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    restart: unless-stopped
    networks:
      - hardwaretech-network   
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  hardwaretech-network:
    external: true    